-- MySQL Script generated by MySQL Workbench
-- 12/14/15 23:36:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `events` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `events` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `events` ;

-- -----------------------------------------------------
-- Table `mydb`.`o_orte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`o_orte` (
  `o_plz` SMALLINT(6) NOT NULL,
  `o_ort` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`o_plz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vr_veranstalter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`vr_veranstalter` (
  `vr_vrnr` INT NOT NULL AUTO_INCREMENT,
  `vr_name` VARCHAR(45) NOT NULL,
  `vr_strasse` VARCHAR(45) NOT NULL,
  `vr_email` VARCHAR(45) NOT NULL,
  `vr_telefon` VARCHAR(45) NOT NULL DEFAULT '111111111111',
  `vr_passwort` VARCHAR(45) NOT NULL,
  `vr_o_plz` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`vr_vrnr`),
  INDEX `fk_vr_veranstalter_o_orte1_idx` (`vr_o_plz` ASC),
  CONSTRAINT `fk_vr_veranstalter_o_orte1`
    FOREIGN KEY (`vr_o_plz`)
    REFERENCES `events`.`o_orte` (`o_plz`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`l_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`l_location` (
  `l_mnr` INT NOT NULL AUTO_INCREMENT,
  `l_latitude` FLOAT(10,6) NOT NULL,
  `l_longitude` FLOAT(10,6) NOT NULL,
  `l_type` VARCHAR(45) NOT NULL,
  `l_name` VARCHAR(45) NOT NULL,
  `l_strasse` VARCHAR(45) NOT NULL,
  `l_o_plz` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`l_mnr`),
  INDEX `fk_m_markers_o_orte1_idx` (`l_o_plz` ASC),
  CONSTRAINT `fk_m_markers_o_orte1`
    FOREIGN KEY (`l_o_plz`)
    REFERENCES `events`.`o_orte` (`o_plz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vg_veranstaltungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`vg_veranstaltungen` (
  `vg_vgnr` INT NOT NULL AUTO_INCREMENT,
  `vg_anfang` DATETIME NOT NULL,
  `vg_name` VARCHAR(45) NOT NULL,
  `vg_vr_vrnr` INT NOT NULL,
  `vg_ende` DATETIME NULL,
  `vg_art` VARCHAR(45) NOT NULL,
  `vg_mitwirkende` TEXT NULL,
  `vg_kurzbeschreibung` TEXT NOT NULL,
  `vg_detailbeschreibung` MEDIUMTEXT NOT NULL,
  `vg_karteninfo` TEXT NOT NULL,
  `vg_plakat` BLOB NULL,
  `vg_kartengesamt` SMALLINT(6) NULL,
  `vg_m_mnr` int NULL,
  PRIMARY KEY (`vg_vgnr`),
  INDEX `fk_vg_veranstaltung_vr_veranstalter_idx` (`vg_vr_vrnr` ASC),
  INDEX `fk_vg_veranstaltungen_m_markers1_idx` (`vg_m_mnr` ASC),
  CONSTRAINT `fk_vg_veranstaltung_vr_veranstalter`
    FOREIGN KEY (`vg_vr_vrnr`)
    REFERENCES `events`.`vr_veranstalter` (`vr_vrnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vg_veranstaltungen_m_markers1`
    FOREIGN KEY (`vg_m_mnr`)
    REFERENCES `events`.`l_location` (`l_mnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`b_besucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`b_besucher` (
  `b_bnr` INT NOT NULL AUTO_INCREMENT,
  `b_username` VARCHAR(45) NOT NULL,
  `b_vorname` VARCHAR(45) NOT NULL,
  `b_nachname` VARCHAR(45) NOT NULL,
  `b_email` VARCHAR(45) NOT NULL,
  `b_telefon` VARCHAR(45) NULL,
  `b_passwort` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`b_bnr`),
  UNIQUE INDEX `b_username_UNIQUE` (`b_username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`r_reservierungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`r_reservierungen` (
  `r_vg_vgnr` INT NOT NULL,
  `r_b_bnr` INT NOT NULL,
  `r_anzahlkarten` SMALLINT NOT NULL,
  PRIMARY KEY (`r_vg_vgnr`, `r_b_bnr`),
  INDEX `fk_r_reservierungen_vg_veranstaltungen1_idx` (`r_vg_vgnr` ASC),
  INDEX `fk_r_reservierungen_b_besucher1_idx` (`r_b_bnr` ASC),
  CONSTRAINT `fk_r_reservierungen_vg_veranstaltungen1`
    FOREIGN KEY (`r_vg_vgnr`)
    REFERENCES `events`.`vg_veranstaltungen` (`vg_vgnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_reservierungen_b_besucher1`
    FOREIGN KEY (`r_b_bnr`)
    REFERENCES `events`.`b_besucher` (`b_bnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vp_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`vp_profile` (
  `vp_vr_vrnr` INT NOT NULL,
  `vp_foto` BLOB NOT NULL,
  `vp_beschreibung` TEXT NOT NULL,
  `vp_website` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vp_vr_vrnr`),
  CONSTRAINT `fk_vp_profile_vr_veranstalter1`
    FOREIGN KEY (`vp_vr_vrnr`)
    REFERENCES `events`.`vr_veranstalter` (`vr_vrnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`k_kommentare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `events`.`k_kommentare` (
  `k_vg_vgnr` INT NOT NULL,
  `k_b_bnr` INT NOT NULL,
  `k_bewertung` TINYINT(4) NULL,
  `k_kommentar` TEXT NOT NULL,
  `k_foto` BLOB NULL,
  PRIMARY KEY (`k_vg_vgnr`, `k_b_bnr`),
  INDEX `fk_k_kommentare_vg_veranstaltungen1_idx` (`k_vg_vgnr` ASC),
  INDEX `fk_k_kommentare_b_besucher1_idx` (`k_b_bnr` ASC),
  CONSTRAINT `fk_k_kommentare_vg_veranstaltungen1`
    FOREIGN KEY (`k_vg_vgnr`)
    REFERENCES `events`.`vg_veranstaltungen` (`vg_vgnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_k_kommentare_b_besucher1`
    FOREIGN KEY (`k_b_bnr`)
    REFERENCES `events`.`b_besucher` (`b_bnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
